# Generated by Django 3.0.4 on 2020-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200404_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('journalism', 'Journalism'), ('biology', 'Biology'), ('physics', 'Physics'), ('IT', 'IT'), ('chemistry', 'Chemistry'), ('economy', 'Economy'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
